### ISSUE TITLE
Use dedicated network

### ISSUE THREAD

**Issue by adlerweb** [volkszaehler/docker#2]
To further improve the separation between the VZ-services and other containers communication should be relocated to a dedicated network - should work something like this:

```
version: "3.1"
services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    working_dir: /application
#    volumes:
#      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=volkszaehler
      - MYSQL_DATABASE=volkszaehler
      - MYSQL_USER=vz
      - MYSQL_PASSWORD=demo
    networks:
      - vznet

  volkszaehler:
    image: volkszaehler
#    build: ./image
    container_name: runtime
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - vznet

networks:
  vznet:
    driver: bridge
```
